[workspace]

members = [
    "doom",
    "engine_core",
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.14.0", default-features = false, features = ["bevy_state"] }
derive_more = "0.99.18"
rustc-hash = "2.0.0"
sdl2 = { version = "0.37.0", default-features = false }
