[package]
name = "exit"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bevy = { workspace = true }
game-state = { path = "../game-state" }
sys-fail = { path = "../../macros/sys-fail" }
