[package]
name = "sys-fail"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
anyhow = { workspace = true }
bevy = { workspace = true }
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full", "proc-macro", "parsing", "clone-impls"] }
